### ISSUE TITLE
`ct install` skipped on manual workflow trigger

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/data-exchange-test-service#31]
The [Chart testing workflow](https://github.com/eclipse-tractusx/data-exchange-test-service/blob/main/.github/workflows/helm-test.yaml#L94) is skipping the `ct install` step on manual `workflow_dispatch`. This is caused by a condition, that only runs the step, if the Chart has changes to the last run.
On a manual trigger, the Chart won't have changes, since they have been released by automated workflows before.
The purpose of the `workflow_dispatch` trigger is to verify, if the Chart can be installed on a given Kubernetes version on demand, like in the current quality gate reviews.

Either the conditional on the workflow step has to be removed, or altered in a way, that it is always run on `workflow_dispatch` events

Manual tests could be done this time, so not necessarily blocking #19

**Comment by SebastianBezold** [comment]
Hi @adkumar1,

the changes from #32 actually did not fix the issue.
The condition on the [workflow step](https://github.com/eclipse-tractusx/data-exchange-test-service/blob/main/.github/workflows/helm-test.yaml#L96) is skipping the `ct install` step

**Comment by adkumar1** [comment]
Changes have been mad in PR #33
